# Generated by Django 2.2.3 on 2019-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='is_sideboard',
            field=models.BooleanField(default=False),
        ),
    ]
