# Generated by Django 2.2.3 on 2019-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20190807_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='is_sideboard',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='sideboard_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
