# Generated by Django 2.2.3 on 2019-07-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manaCost', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True)),
                ('fancyText', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=2)),
                ('toughness', models.CharField(blank=True, max_length=2)),
                ('loyalty', models.CharField(blank=True, max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('addMana', models.BooleanField()),
                ('count', models.SmallIntegerField(default=0)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typeType', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardTypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Type')),
            ],
        ),
        migrations.CreateModel(
            name='CardSetMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Set')),
            ],
        ),
    ]
